---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-eaton-ups-exporter-config
data:
  config.json: ewogICAgInVwczFfbmFtZSI6IHsKICAgICAgICAiYWRkcmVzcyI6ICJodHRwczovL2FkZHJlc3MudG8udXBzMSIsCiAgICAgICAgInVzZXIiOiAidXNlcm5hbWUiLAogICAgICAgICJwYXNzd29yZCI6ICJwYXNzd29yZCIKICAgIH0sCiAgICAidXBzMl9uYW1lIjogewogICAgICAgICJhZGRyZXNzIjogImh0dHBzOi8vYWRkcmVzcy50by51cHMyIiwKICAgICAgICAidXNlciI6ICJ1c2VybmFtZSIsCiAgICAgICAgInBhc3N3b3JkIjogInBhc3N3b3JkIgogICAgfQp9Cg== 

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: prometheus-eaton-ups-exporter 
spec:
   replicas: 1
   selector:
      matchLabels:
         app: prometheus-eaton-ups-exporter
   template:
      metadata:
         labels:
            app: prometheus-eaton-ups-exporter
      spec:
         containers:
            - name: prometheus-eaton-ups-exporter
              image: adyekjaer/prometheus-eaton-ups-exporter:3
              imagePullPolicy: IfNotPresent
              command: ["python"]
              args: ["./prometheus_eaton_ups_exporter.py", "-k", "-c", "/usr/src/app/etc/config.json","-w","0.0.0.0:9795"]
              volumeMounts:
                - mountPath: "/usr/src/app/etc"
                  name: config
                  readOnly: true
         volumes:
           - name: config
             secret:
               secretName: prometheus-eaton-ups-exporter-config
---
apiVersion: v1
kind: Service
metadata:
   name: prometheus-eaton-ups-exporter
spec:
   type: ClusterIP
   selector:
      app: prometheus-eaton-ups-exporter
   ports:
      - port: 9795
        targetPort: 9795
